### ISSUE TITLE
Problem with reactivity

### ISSUE THREAD

**Issue by murilopolese** [Molecule-JS/MoleculeJS#45]
Hey! I love your project and I'm committed to use it on my new project.

I notice on the other hand a few things that might be a bug, lack of documentation or a bigger problem between my screen and my chair!

The first one is that this bit of documentation ([Examples](https://github.com/Molecule-JS/MoleculeJS/blob/master/README.md#examples) on `README.md`) looks kinda wrong: 

```javascript
class HelloWorld extends MoleculeLit.Element {
  static get properties() {
    return {
      name: String,
      attribute: true,
      value: 'John Doe',
    };
  }
...
```

I guess it should be something like:

```javascript
class HelloWorld extends MoleculeLit.Element {
  static get properties() {
    return {
      name: { 
        type: String,
        attribute: true,
        value: 'John Doe'
      }
    };
  }
...
```

I also notice that if I declare the property as an attribute, when I call `this.setProperty('name', 'Foo')` it does update the attribute but it won't update the rendered template. I was expecting it to update the template no matter if it's an attribute or an internal property... Am I making a wrong assumption?

```javascript
import { html, render } from './node_modules/lit-html/lit-html.js'
import { Element } from './node_modules/@moleculejs/molecule/dist/molecule.mjs'
const ElementLit = Element(render)
class TestElement extends ElementLit {
	static get properties() {
		return {
			name: {
				type: String,
				attribute: true, // If I comment this line it updates
				value: 'Lala'
			}
		}
	}
	changeName(self, e) {
		this.setProperty('name', 'Dinky Winky')
	}
	render({msg}) {
		return html`
			<h1>Name: ${name}</h1>
			<button @click=${this.changeName.bind(this)}>Change name</button>
		`
	}
}
customElements.define('test-element', TestElement)
```

I'm tried on `Firefox 63.0.3 (64-bit)` and on `Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)` both on Ubuntu 18.04.

**Comment by DerDrodt** [comment]
Hey! Awesome that you like the project. 
First: Yeah, that’s a mistake. Thank you for that, I’ll correct it ASAP. Or feel free to create a PR, if you have the time. 

Second: You assume correctly. That sounds like a bug. I’ll look into it over the next few days. 

Thank you for letting me know.

**Comment by DerDrodt** [comment]
Fixed the wrong example

**Comment by murilopolese** [comment]
Cool, @DerDrodt !!!! I had a bit of a busy day but I will have a look at the second issue as well, I really wanna dig the code to learn how you achieved such awesomeness :D

**Comment by DerDrodt** [comment]
Feel free to do that. But I think I found it.

1. Your example had a small mistake. In your parameters of `render`, you wrote `{msg}`, but the property is called `name`. That one took me a while to see :)
2. `name` already is an attribute on HTML and in some cases it behaves a bit weird. That shouldn't be relevant here, but just keep that in mind. I had a few bugs with that (I should add that to the docs)
3. This was the actual mistake: For whatever reason, if we have an attribute that updates, and we "force" an update (like you did with `setProperty`) we just do nothing. I don't know why I wrote it that way, but that was the issue. I'll investigate a bit and publish a new version.

Thank you for reporting this bug. If you find another one, please let me know!

**Comment by murilopolese** [comment]
Oh, sorry, that was a bad translation from the actual code (where I was using `msg` and not `name`) but the misbehaviour is still present using either `name` or `msg`.

I'll definitely keep in mind to avoid using standard attributes. I believe in Polymer they append something to make explicit whether using a custom or a default attribute., that could be a lead.

I'm so happy I helped somehow, I hope to level up to be able to make an actual code contribution next time! :smiley: 

Would you like me to close this issue or keep it open to track when the possible fix is out?

**Comment by DerDrodt** [comment]
The commit that fixed it closed it automatically.

> Oh, sorry, that was a bad translation from the actual code (where I was using msg and not name) but the misbehaviour is still present using either name or msg.

No worries, I already assumed something like that.

> I'll definitely keep in mind to avoid using standard attributes. I believe in Polymer they append something to make explicit whether using a custom or a default attribute., that could be a lead.

Didn't know about that. But I do know that they don't do it anymore in LitElement.

> I'm so happy I helped somehow, I hope to level up to be able to make an actual code contribution next time! smiley

Well if you have any ideas or want a place to start, I'd be happy to help.
